import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "K Scan AI",
    short_name: "K Scan",
    description: "Fashion, made shoppable.",
    start_url: "/",
    display: "standalone",
    background_color: "#09090b",
    theme_color: "#09090b",
    orientation: "portrait-primary",
    icons: [
      // SVG — scales to any size, supported by modern Android Chrome
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      // PNG fallbacks — generated by app/icon.tsx (48×48)
      // and a 512×512 export you can add to /public/icon-512.png
      // using: npx sharp-cli input /app/icon.svg output /public/icon-512.png resize 512 512
      {
        src: "/icon",
        sizes: "48x48",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
